SUDO ?= sudo
CMAKE_FLAGS ?= 

PROJECT_DIR := $(shell pwd)
MAIN_DIR := $(PROJECT_DIR)/main
COMPONENTS_DIR := $(PROJECT_DIR)/components
REQUIREMENTS_DIR := $(PROJECT_DIR)/requirements
SCRIPTS_DIR := $(PROJECT_DIR)/scripts
BUILD_DIR := $(PROJECT_DIR)/build
TOOLS_DIR := $(PROJECT_DIR)/tools
